52 setup server
BKFPML/fundamental-app pull request #62
Opened 2024-11-28 06:53 UTC by KentinPaille

Initialisation of server api route, creation of the nest back-end and function to get ETH Balance and Token balance on the blockchain BASE

2024-11-30 14:58 UTC, PaulThblt commented on client/.gitignore
> +# @end expo-cli
```suggestion
# @end expo-cli

```

2024-11-30 14:59 UTC, PaulThblt commented on client/package.json
> +    "@types/node": "^22.9.0",
Do we need this in the client?

2024-11-30 15:00 UTC, PaulThblt commented on server/.prettierrc
> +}
```suggestion
}

```

2024-11-30 15:00 UTC, PaulThblt commented on server/README.md
Get rid of this?

2024-11-30 15:01 UTC, PaulThblt commented on server/netlify/functions/TokenBalances/TokenBalances.ts
> +};
```suggestion
};

```

2024-11-30 15:06 UTC, PaulThblt commented
Good stuff but I think that we really need to have a separate repo for this

2024-11-30 15:12 UTC, PaulThblt requested changes
We need a separate repo

2024-12-01 23:46 UTC, bendsp commented
Good work but I second Paul on the separation. We can discuss tomorrow

2024-12-03 11:50 UTC, closed without merging